# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'book_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for book_app

pod 'Firebase/Core'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'

pod 'SDWebImage'
end
